## Activity 01: Use NumPy to compute the Mean, Median, and Variance

In this activity, you will consolidate the skills you've acquired in the last exercise and use NumPy to do some very basic mathematical calculations on our `normal_distribution` dataset.   
NumPy has a consistent API, so it should be rather easy to transfer your knowledge of the mean method to median and variance. 

#### Loading the dataset

In [1]:
# importing the necessary dependencies
import numpy as np
import pandas as pd

In [2]:
# loading the Dataset
dataset = np.genfromtxt('./data/normal_distribution.csv', delimiter=',')

In [3]:
# looking at the first two rows of the dataset
df = pd.DataFrame(dataset, columns = ['A','B','C','D','E','F','G','H'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       24 non-null     float64
 1   B       24 non-null     float64
 2   C       24 non-null     float64
 3   D       24 non-null     float64
 4   E       24 non-null     float64
 5   F       24 non-null     float64
 6   G       24 non-null     float64
 7   H       24 non-null     float64
dtypes: float64(8)
memory usage: 1.6 KB


In [4]:
df.head()

A           B           C           D           E           F   
0   99.149315  104.038527  107.435347   97.852307   98.749869   98.808334  \
1   92.026288   97.104393   99.320669   97.245848   92.926751   92.656578   
2   95.662537   95.177501   90.933181  110.188895   98.800844  105.952977   
3   91.372946  100.967814  100.401183  113.420905  105.485088   91.660495   
4  101.208625  103.573031  100.286909  105.852694   93.371263  108.579804   

            G           H  
0   96.819649   98.567832  
1  105.719785  101.231629  
2   98.374814  106.546543  
3  106.147284   95.087158  
4  100.794790   94.200197

In [5]:
df.tail()

A           B           C           D           E           F   
19   96.768148   91.677922  101.791328  101.207734   98.292440  101.838458  \
20  106.890050  106.573646  102.266483  107.400646   99.943182  103.404121   
21   99.808731  101.639731  106.464765  110.439767  100.691562   99.995795   
22   96.100203   94.574217  100.804093  105.023899   98.613252   95.623593   
23   94.111769   99.623878  104.517864   97.627878   93.978535   98.751084   

             G           H  
19   97.940469  102.206185  
20  106.382767   98.002530  
21  101.321137   94.762536  
22   97.997624  103.838525  
23  106.050425  100.077215

---

#### Mean

In [6]:
# calculate the mean of the third row
dataset[3].mean()

100.56785907

In [29]:
# calculate the mean of the last column
dataset[:,-1].mean()

100.4404927375

In [50]:
# calculate the mean of the intersection of the first 3 rows and first 3 columns
intersection = dataset[:3,:3]
# print(intersection)

print('DF:',df.head(3).iloc[:,:3].mean().mean())
print('Np:',np.mean(intersection))

DF: 97.87197312333335
Np: 97.87197312333333


---

#### Median

In [46]:
# calculate the median of the last row
print('np:',np.median(dataset[-1]))
print('df:',df.iloc[-1].median())

np: 99.18748092
df: 99.18748092


In [111]:
# calculate the median of the last 3 columns

print('np med:',np.median(dataset[:,-3:]))

np med: 99.47332349999999


In [102]:
# calculate the median of the last 3 columns
print('dense:',df.iloc[:,-3:].median())

dense: F     99.084167
G     98.798908
H    100.605820
dtype: float64


In [109]:
# calculate the median of each row

np.median(dataset, axis=1)

array([ 98.77910163,  97.17512034,  98.58782879, 100.68449836,
       101.00170737,  97.76908825, 101.85002253, 100.04756697,
       102.24292555,  99.59514997, 100.4955753 ,  99.8860714 ,
        99.00647994,  98.67276177, 102.44376222,  96.61933565,
       104.0968893 , 100.72023043,  98.70877396,  99.75008654,
       104.89344428, 101.00634942,  98.30543801,  99.18748092])

---

#### Variance

In [116]:
# calculate the variance of each column
np.var(dataset, axis=0)

array([23.64757465, 29.78886109, 20.50542011, 26.03204443, 28.38853175,
       19.09960817, 17.67291174, 16.17923204])

In [128]:
# calculate the variance of the intersection of the last 2 rows and first 2 columns
dataset[-2:,:2]

array([[96.10020311, 94.57421727],
       [94.11176915, 99.62387832]])

The values of the variance might seem a little bit strange at first.   
You can always go back to the topic that gives you a quick statistical overview to recap what you've learned so far.   

> **Note:**   
Just remember, the variance is not the standard deviation.   

Try calculation the standard deviation with NumPy to get a more descriptive value when comparing it to our dataset

In [129]:
# calculate the standard deviation for the dataset
np.std(dataset)

4.838197554269257