## Hsplit vs Vsplit

In [3]:
# hsplit, vsplit

import numpy as np

a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
result = np.vsplit(a, 2) # row-wise split
print(result)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [8]:
result = np.hsplit(a, 2) # column-wise split
print(result)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


## Reshaping

In [17]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
a.reshape(4,-1).shape

(4, 4)

In [16]:
a.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

## iloc vs loc

In [18]:
import pandas as pd

# Create a DataFrame
technologies = {
    'Courses':["Spark","PySpark","Hadoop","Python","pandas"],
    'Fee' :[20000,25000,26000,22000,24000],
    'Duration':['30day','40days','35days','40days','60days'],
    'Discount':[1000,2300,1200,2500,2000]
}

index_labels=['r1','r2','r3','r4','r5']
df = pd.DataFrame(technologies,index=index_labels)
print(df)


    Courses    Fee Duration  Discount
r1    Spark  20000    30day      1000
r2  PySpark  25000   40days      2300
r3   Hadoop  26000   35days      1200
r4   Python  22000   40days      2500
r5   pandas  24000   60days      2000


In [19]:
# Select Multiple Rows by Label
print(df.loc[['r2','r3']])

    Courses    Fee Duration  Discount
r2  PySpark  25000   40days      2300
r3   Hadoop  26000   35days      1200


In [88]:
# Select Multiple Rows by Index
print(df.iloc[[1,2]])

    Courses    Fee Duration  Discount
r2  PySpark  25000   40days      2300
r3   Hadoop  26000   35days      1200


In [58]:
# Select Multiple Columns by labels
print(df.loc[:, ["Courses","Fee","Discount"]])

    Courses    Fee  Discount
r1    Spark  20000      1000
r2  PySpark  25000      2300
r3   Hadoop  26000      1200
r4   Python  22000      2500
r5   pandas  24000      2000


In [90]:
df.iloc[:3,:2]

Courses    Fee
r1    Spark  20000
r2  PySpark  25000
r3   Hadoop  26000

In [91]:
# Select Multiple Columns by Index
df.iloc[2:4]

Courses    Fee Duration  Discount
r3  Hadoop  26000   35days      1200
r4  Python  22000   40days      2500

## Mean, Median

In [56]:
df['Fee'].head(5).var()

5800000.0

In [93]:
# iteration

for index, row in df.iterrows():
    print(index,  '> ',row.to_list())

r1 >  ['Spark', 20000, '30day', 1000]
r2 >  ['PySpark', 25000, '40days', 2300]
r3 >  ['Hadoop', 26000, '35days', 1200]
r4 >  ['Python', 22000, '40days', 2500]
r5 >  ['pandas', 24000, '60days', 2000]
